### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by bianjingbulb** [kitasuke/PagingMenuController#161]
Hi, friend!
Thanks for your contribution.
I read your code and found lazy loading function.
Does that really work?
If so, can you tell how to use lazy loading function please?
Thanks a lot.

**Comment by bianjingbulb** [comment]
I realized it loads 2 pages at once, Can it just load one page at once?

**Comment by kitasuke** [comment]
Currently its for 3 view controllers(left, center and right).
I'll make a new option for that case!

**Comment by jacksonWii** [comment]
Good issue.
I had the same problem.

I have three tableViewControllers as child viewController.
Each child tableViewController is getting json data from server.
My app keep crashing all the time cause of the three tableViewControllers load data at the same time.

I hope it can just load one child page (current displaying page on screen)  at a time.
For example, there are  vc1, vc2, vc3 as child viewControllers.
When the app started, just load vc1. And then, when the user slide to the vc2, the vc2 get started on loading data. 

Thanks a lot !

**Comment by bianjing** [comment]
My app crashed too ......
And I think this issue is probably the reason.
I have 3 child-VCs, and each child-VC loads some pictures(very large) to tableViewCell.
Because 3 child-VCs load pictures at the same time , my app got memory warning and then crashed.
I hope my child VC load data from server only when it is  active.

**Comment by CocosWong** [comment]
My app crashed too ......
And I think this issue is probably the reason.
I have 3 child-VCs, and each child-VC loads some pictures(very large) to tableViewCell.
Because 3 child-VCs load pictures at the same time , my app got memory warning and then crashed.
I hope my child VC load data from server only when it is active.

**Comment by kitasuke** [comment]
Can you check my PR above whether it fixes the issue, @bianjingbulb, @jacksonWii, @CocosWong ?
You will notice that scrolling paging view is disabled for now though.

**Comment by bianjingbulb** [comment]
I  pulled code and ran "pod install" at  branch/support_one_lazy_loading.

I tested at "PagingMenuContrllerDemo" by adding `print("here is n")` to each child ViewController's(UsersVC, RepositoriesVC, GistsViewVC and OrganizationsVC) 
`override func viewDidLoad(){}`  function .

The result is as follow,
`here is one! `
`here is two!`

So, it keeps loading two  pages at once.

**Comment by kitasuke** [comment]
I completely forgot to write usage.
Please add code below.

`options.lazyLoadingPage = .One`

**Comment by bianjingbulb** [comment]
It worked !!!

**Comment by kitasuke** [comment]
It's pre-released. Please use the latest version.
