### ISSUE TITLE
PageMenu Knock Off

### ISSUE THREAD

**Issue by fahlout** [kitasuke/PagingMenuController#17]
This library is very much leaning on my library [PageMenu](https://github.com/uacaps/PageMenu), which is just not okay. From the naming to the customization options they are pretty much the same..

**Comment by kitasuke** [comment]
@fahlout Sorry about that, but it's not like I just imitated your library. I wanted to make it simple, so I named in this way. I believe that the terms are generally used.
Plus, it might sound like same naming because it doesn't have a prefix since Swift supports namespace.

However, the customization options are not the same like scrolling mode or menu item design mode and the way it constructs it's view is totally different from PageMenu.

**Comment by fahlout** [comment]
a lot of the customization options are the same and the different modes like segmented control mode are definitely the same... at least admit that my library was a guideline for yours

**Comment by kitasuke** [comment]
Yes, it's inspired by PageMenu a lot. Can I write `This library is inspired by PageMenu` in description?

Well, setting options as key and values or as property is not the same.
It's safer not to typo for key name and any options won't be ignored if it's property.
I know this library is not better than yours in terms of memory management since it's still developing.
 Could you tell me what's wrong with memory management?
Thanks in advance.

**Comment by kitasuke** [comment]
I got your point FINALLY. I didn't know you already supported AutoLayout and option enum. Because last time I saw your library was this commit `f632e02b67ab42636f8655ea5b0aaf854598c11d `. At that time, there wasn't such things, so I just decided to create my own library which looks similar now...
Sorry for this situation, but this was what I needed earlier.

**Comment by fahlout** [comment]
Since it's all open source it is okay for you to base your library on someone elses. My point was just that you should give credit to that person. So yes, I would like you to write something like you mentioned 'This library is inspired by PageMenu' and it should include a link to PageMenu https://github.com/uacaps/PageMenu

**Comment by kitasuke** [comment]
Ok, I added into README.md. Please check it out. Thanks!

**Comment by exalted** [comment]
I enjoyed this convo of you two... Especially @kitasuke 's calm and collaborative attitude!

Kudos and keep up the good work, both of you. 👏
