### ISSUE TITLE
How to use Image view instead of label for menu title?

### ISSUE THREAD

**Issue by SuYungCheng** [kitasuke/PagingMenuController#219]
I use Label for menu title before:
Code:
```
let viewController = UIViewController()
viewController.title = "title1"
let viewController2 = UIViewController()
viewController2.title = "title2"
let viewControllers = [viewController,viewController2]
```
[Before](http://i.imgur.com/X4C3CZP.jpg)
But now want to use one image and one Label.
Code:
```
let viewController2 = UIViewController()
viewController2.menuItemImage = UIImage(named: "addPic")
```
[After](http://i.imgur.com/jnPxOH5.jpg)
It is big and title1 is gone.
Can someone teach me how to use that?
Thanks!

**Comment by kitasuke** [comment]
I'll change constriants of image to horizontally/vertically center and fix this issue.

**Comment by SuYungCheng** [comment]
If I ViewController1 use "menuItemImage" change label to image,
and ViewController2 still keep label by use ".title" to set String.
Why label is disappear?
Where I make mistake?

```

        viewController.menuItemImage = UIImage(named: "image")

        viewController2.title = "DIY"
```

**Comment by kitasuke** [comment]
Because showing image on menu item is still beta feature.
You cannot set different types on menu item right now, so if you set an image to menuItemImage of viewController1, all the menu item is supposed to show an image.
However, I understand that you want to mix types like image and title on different menu item, so I'll support it soon.

**Comment by kitasuke** [comment]
Please use 1.0.0 version.
