### ISSUE TITLE
Access parent view controller

### ISSUE THREAD

**Issue by Sorix** [kitasuke/PagingMenuController#269]
How to access parent view controller from pages view controllers?

1. In child view controller `self.parentViewController` is always `nil`. I think it is incorrect (maybe you haven't called didMove for each child view controller in your framework?).
2. As you discussed in #254 I can try to use `willMoveToPageMenuController`, but that method is not called when you're initially loaded view controller (e.g. first page).

**Comment by kitasuke** [comment]
I'm not sure for your case, but accessing parent view controller means that child view controller relies on parent view controller which is not a good way for most cases.
1. It does here. https://github.com/kitasuke/PagingMenuController/blob/master/Pod/Classes/PagingViewController.swift#L120:L121
2. It doesn't call these delegate method because initial load is not considered as moving menu.

**Comment by Sorix** [comment]
> It doesn't call these delegate method because initial load is not considered as moving menu.

So how can I get access to initially loaded controller? I know how to access controllers when it's get moved, but how can I access currently loaded controller?

**Comment by Sorix** [comment]
Solution:

```swift
		let pagingMenuController = viewController.childViewControllers.first as! PagingMenuController
		print(pagingMenuController.pagingViewController?.currentViewController)
		print(pagingMenuController.pagingViewController?.controllers)
```
